[package]
name = "ffmpeg-install-script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "^0.11"
indicatif = "^0.17.3"
tokio = {version = "1.28.1", features = ["full"]}
zip = "0.6.6"